CREATE TABLE [dbo].[Artefacts]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Nom] VARCHAR(MAX) NOT NULL,
	[NomSet] VARCHAR(MAX) NOT NULL,
	[Type] VARCHAR(50) NOT NULL,
	[Bonus2Pieces] VARCHAR(MAX) NOT NULL,
	[Bonus4Pieces] VARCHAR(MAX) NOT NULL,
	[ImagePath] VARCHAR(MAX) NOT NULL,
	[Source] VARCHAR(MAX) NOT NULL
)
